apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  # The name of the task
  name: build-test-app-task
spec:
  resources:
    inputs:
     - name: git
       type: git
  volumes:
    # Mount the docker socket from the node for building images
    # See the tutorial for more information
    - name: docker-socket
      hostPath:
        type: Socket
        path: /var/run/docker.sock
steps:
# The name of the step
- name: pytest
  image: python:3.9
  command:
  - /bin/bash
  - -c
  args:
  # Changes to the app/ directory, installs required dependencies, and
  # run all the tests with pytest
  - cd /workspace/git/getting-started/src/app && pip3 install -r requirements.txt && pip3 install -r dev_requirements.txt && pytest .
- name: docker
  image: docker
  command:
  - docker
  args:
  - build
  - -f
  - /workspace/git/getting-started/src/Dockerfile
  - -t
  - app
  - /workspace/git/getting-started/src
  # Volumes mounted to support Katacoda single-node K8S environment
  volumes:
  - name: dsocket
    persistentVolumeClaim:
      claimName: dsocket-vol-claim
  - name: dlib
    persistentVolumeClaim:
      claimName: dlib-vol-claim
